#!/usr/bin/env zsh

STOW_FOLDERS="alacritty,tmux,zsh,nvim,starship-prompt,i3"
DOTFILES=$HOME/.dotfiles

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd
