#!/usr/bin/env zsh

STOW_FOLDERS = "alacritty,tmux,zsh,nvim,starship-prompt"
DOTFILES = $HOME/.dotfiles

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing ${folder} from stow"
    stow -D $folder

    echo "Stowing ${folder}"
    stow $folder
done
popd
